---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - policy
  resources:
  - kubeteuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - kubeteuses/finalizers
  verbs:
  - update
- apiGroups:
  - policy
  resources:
  - kubeteuses/status
  verbs:
  - get
  - patch
  - update
